name: Build

on:
  workflow_call:
    inputs:
      dotnet-sdk:
        required: true
        type: string
      main-project:
        required: true
        type: string
      artifact-name-prefix:
        required: true
        type: string
      is-tool:
        required: true
        type: boolean
    secrets:
      es-username:
        required: true
      es-password:
        required: true
      es-credential-id:
        required: true
      es-totp-secret:
        required: true
        
env:
  PUBLISH_ANY_PATH: ./bin/publish/any
  PUBLISH_FDE_WIN_PATH: ./bin/publish/fde/win-x64
  PUBLISH_FDE_WIN_ARM64_PATH: ./bin/publish/fde/win-arm64
  PUBLISH_FDE_OSX_PATH: ./bin/publish/fde/osx-x64
  PUBLISH_FDE_OSX_ARM64_PATH: ./bin/publish/fde/osx-arm64
  PUBLISH_FDE_LINUX_PATH: ./bin/publish/fde/linux-x64
  PUBLISH_FDE_LINUX_ARM64_PATH: ./bin/publish/fde/linux-arm64
  PUBLISH_SCD_WIN_PATH: ./bin/publish/scd/win-x64
  PUBLISH_SCD_WIN_ARM64_PATH: ./bin/publish/scd/win-arm64
  PUBLISH_SCD_OSX_PATH: ./bin/publish/scd/osx-x64
  PUBLISH_SCD_OSX_ARM64_PATH: ./bin/publish/scd/osx-arm64
  PUBLISH_SCD_LINUX_PATH: ./bin/publish/scd/linux-x64
  PUBLISH_SCD_LINUX_ARM64_PATH: ./bin/publish/scd/linux-arm64
  NUPKG_PATH: ./bin/nupkg/any
  PACKAGE_VERSION_FILE: ./version.txt
  
jobs:
  build-test:
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm, macos-latest, ubuntu-latest, ubuntu-24.04-arm]
        configuration: [Debug, Release]
        include:
          - os: ubuntu-latest
            configuration: Debug
            cache: true

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: recursive
        
    - name: Cache checkout
      if: ${{ matrix.cache }}
      uses: actions/cache/save@v5
      with:
        path: ${{ github.workspace }}
        key: checkout-${{ github.run_id }}-${{ github.run_attempt }}
          
    - name: Use dotnet sdk
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-sdk }}

    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}

    - name: Test
      run: dotnet test -c ${{ matrix.configuration }} --no-build
           
  package:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - name: Cache checkout
      id: cache-checkout
      uses: actions/cache/restore@v5
      with:
        path: ${{ github.workspace }}
        key: checkout-${{ github.run_id }}-${{ github.run_attempt }}
        
    - name: Checkout
      if: steps.cache-checkout.outputs.cache-hit != 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Use dotnet sdk
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-sdk }}

    - name: Set non-main branch version build number
      if: github.ref != 'refs/heads/main'
      run: | 
        version=$(grep -oPm1 "(?<=<Version>)[^<]+" ${{ inputs.main-project }})
        echo "Got version from project - '$version'"

        first_part_version=$version
        if [[ "$version" == *"-"* ]]; then
          first_part_version="${version%%-*}"
        fi

        new_version="${first_part_version}-build.${{ github.run_number }}"
        echo "New version - '$new_version'"
        echo "Old version - '$version'"
        sed -i "s|<Version>$version</Version>|<Version>$new_version</Version>|" ${{ inputs.main-project }}

    - name: Get package version
      run: |
        version=$(grep -oPm1 "(?<=<Version>)[^<]+" ${{ inputs.main-project }})
        echo "Got version - '$version'"
        echo "VERSION=$version" >> ${{ env.PACKAGE_VERSION_FILE }}
        
    - name: Publish release [fdd-any]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} -p:UseAppHost=false -o $PUBLISH_ANY_PATH

    - name: Nuget Pack
      run: dotnet pack ${{ inputs.main-project }} -o $NUPKG_PATH  
      
    - name: FDE and SCD Prep
      if: ${{ inputs.is-tool }}     
      run: |
        sed -i "s|<PublishSingleFile>false</PublishSingleFile>|<PublishSingleFile>true</PublishSingleFile>|" ${{ inputs.main-project }}
        
    - name: Publish release [fde-win-x64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --no-self-contained -r win-x64 -o $PUBLISH_FDE_WIN_PATH

    - name: Publish release [fde-win-arm64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --no-self-contained -r win-arm64 -o $PUBLISH_FDE_WIN_ARM64_PATH

    - name: Publish release [fde-osx-x64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --no-self-contained -r osx-x64 -o $PUBLISH_FDE_OSX_PATH
      
    - name: Publish release [fde-osx-arm64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --no-self-contained -r osx-arm64 -o $PUBLISH_FDE_OSX_ARM64_PATH

    - name: Publish release [fde-linux-x64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --no-self-contained -r linux-x64 -o $PUBLISH_FDE_LINUX_PATH
      
    - name: Publish release [fde-linux-arm64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --no-self-contained -r linux-arm64 -o $PUBLISH_FDE_LINUX_ARM64_PATH
      
    - name: Publish release [scd-win-x64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --self-contained -r win-x64 -o $PUBLISH_SCD_WIN_PATH

    - name: Publish release [scd-win-arm64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --self-contained -r win-arm64 -o $PUBLISH_SCD_WIN_ARM64_PATH
      
    - name: Publish release [scd-osx-x64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --self-contained -r osx-x64 -o $PUBLISH_SCD_OSX_PATH

    - name: Publish release [scd-osx-arm64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --self-contained -r osx-arm64 -o $PUBLISH_SCD_OSX_ARM64_PATH
      
    - name: Publish release [scd-linux-x64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --self-contained -r linux-x64 -o $PUBLISH_SCD_LINUX_PATH

    - name: Publish release [scd-linux-arm64]
      if: ${{ inputs.is-tool }}
      run: dotnet publish ${{ inputs.main-project }} --self-contained -r linux-arm64 -o $PUBLISH_SCD_LINUX_ARM64_PATH
      
    - name: Cache publish files
      if: ${{ inputs.is-tool }}
      uses: actions/cache/save@v5
      with:
        path: |
          ${{ env.PUBLISH_ANY_PATH }}
          ${{ env.PUBLISH_FDE_WIN_PATH }}
          ${{ env.PUBLISH_FDE_WIN_ARM64_PATH }}
          ${{ env.PUBLISH_FDE_OSX_PATH }}
          ${{ env.PUBLISH_FDE_OSX_ARM64_PATH }}
          ${{ env.PUBLISH_FDE_LINUX_PATH }}
          ${{ env.PUBLISH_FDE_LINUX_ARM64_PATH }}
          ${{ env.PUBLISH_SCD_WIN_PATH }}
          ${{ env.PUBLISH_SCD_WIN_ARM64_PATH }}
          ${{ env.PUBLISH_SCD_OSX_PATH }}
          ${{ env.PUBLISH_SCD_OSX_ARM64_PATH }}
          ${{ env.PUBLISH_SCD_LINUX_PATH }}
          ${{ env.PUBLISH_SCD_LINUX_ARM64_PATH }}
        key: publish-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Cache nuget packages
      uses: actions/cache/save@v5
      with:
        path: |
          ${{ env.NUPKG_PATH }}
          ${{ env.PACKAGE_VERSION_FILE }}
        key: nuget-${{ github.run_id }}-${{ github.run_attempt }}
        
  sign-nuget:
    needs: package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Restore nuget file
      id: nuget-cache
      uses: actions/cache/restore@v5
      with:
        path: |
          ${{ env.NUPKG_PATH }}
          ${{ env.PACKAGE_VERSION_FILE }}
        key: nuget-${{ github.run_id }}-${{ github.run_attempt }}
        fail-on-cache-miss: true

    - name: Get version
      run: |
        . version.txt
        echo $VERSION
        echo "version=$VERSION" | tr -d '\r\n' >> "$GITHUB_ENV"
        
    - name: Sign artifacts (tool)
      if: ${{ inputs.is-tool }}
      uses: sslcom/esigner-codesign@main
      with:
        command: sign
        username: ${{ secrets.es-username }}
        password: ${{ secrets.es-password }}
        credential_id: ${{ secrets.es-credential-id }}
        totp_secret: ${{ secrets.es-totp-secret }}
        file_path: ${{ env.NUPKG_PATH }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}.nupkg
        override: true
        
    - name: Sign artifacts (library)
      if: ${{ !inputs.is-tool }}
      uses: sslcom/esigner-codesign@main
      with:
        command: sign
        username: ${{ secrets.es-username }}
        password: ${{ secrets.es-password }}
        credential_id: ${{ secrets.es-credential-id }}
        totp_secret: ${{ secrets.es-totp-secret }}
        file_path: ${{ env.NUPKG_PATH }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}.nupkg
        override: true

    - name: Rename symbols package for signing
      if: ${{ !inputs.is-tool }}
      run: |
        mv ${{ env.NUPKG_PATH }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}.snupkg \
           ${{ env.NUPKG_PATH }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}.symbols.nupkg

    - name: Sign artifacts (library symbols)
      if: ${{ !inputs.is-tool }}
      uses: sslcom/esigner-codesign@main
      with:
        command: sign
        username: ${{ secrets.es-username }}
        password: ${{ secrets.es-password }}
        credential_id: ${{ secrets.es-credential-id }}
        totp_secret: ${{ secrets.es-totp-secret }}
        file_path: ${{ env.NUPKG_PATH }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}.symbols.nupkg
        override: true

    - name: Rename symbols package back
      if: ${{ !inputs.is-tool }}
      run: |
        mv ${{ env.NUPKG_PATH }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}.symbols.nupkg \
           ${{ env.NUPKG_PATH }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}.snupkg
           
    - name: Cache signed nuget packages
      uses: actions/cache/save@v5
      with:
        path: |
          ${{ env.NUPKG_PATH }}
          ${{ env.PACKAGE_VERSION_FILE }}
        key: nuget-signed-${{ github.run_id }}-${{ github.run_attempt }}
        
  upload-artifacts:
    needs: sign-nuget
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
    - name: Restore publish files
      if: ${{ inputs.is-tool }}
      id: publish-cache
      uses: actions/cache/restore@v5
      with:
        path: |
          ${{ env.PUBLISH_ANY_PATH }}
          ${{ env.PUBLISH_FDE_WIN_PATH }}
          ${{ env.PUBLISH_FDE_WIN_ARM64_PATH }}
          ${{ env.PUBLISH_FDE_OSX_PATH }}
          ${{ env.PUBLISH_FDE_OSX_ARM64_PATH }}
          ${{ env.PUBLISH_FDE_LINUX_PATH }}
          ${{ env.PUBLISH_FDE_LINUX_ARM64_PATH }}
          ${{ env.PUBLISH_SCD_WIN_PATH }}
          ${{ env.PUBLISH_SCD_WIN_ARM64_PATH }}
          ${{ env.PUBLISH_SCD_OSX_PATH }}
          ${{ env.PUBLISH_SCD_OSX_ARM64_PATH }}
          ${{ env.PUBLISH_SCD_LINUX_PATH }}
          ${{ env.PUBLISH_SCD_LINUX_ARM64_PATH }}
        key: publish-${{ github.run_id }}-${{ github.run_attempt }}
        fail-on-cache-miss: true
        
    - name: Restore signed nuget file
      id: nuget-signed-cache
      uses: actions/cache/restore@v5
      if: github.ref == 'refs/heads/main'
      with:
        path: |
          ${{ env.NUPKG_PATH }}
          ${{ env.PACKAGE_VERSION_FILE }}
        key: nuget-signed-${{ github.run_id }}-${{ github.run_attempt }}
        fail-on-cache-miss: true

    - name: Restore nuget file
      id: nuget-cache
      uses: actions/cache/restore@v5
      if: github.ref != 'refs/heads/main'
      with:
        path: |
          ${{ env.NUPKG_PATH }}
          ${{ env.PACKAGE_VERSION_FILE }}
        key: nuget-${{ github.run_id }}-${{ github.run_attempt }}
        fail-on-cache-miss: true
      
    - name: Get version
      run: |
        . version.txt
        echo $VERSION
        echo "version=$VERSION" | tr -d '\r\n' >> "$GITHUB_ENV"
        
    - name: Archive [fdd-any] zip
      if: ${{ inputs.is-tool }}
      run: 7z a -tzip '${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-fdd-any.zip' '${{ env.PUBLISH_ANY_PATH }}'

    - name: Archive [fdd-any] tar
      if: ${{ inputs.is-tool }}
      run: |
        lastPart=$(basename ${{ env.PUBLISH_ANY_PATH }})
        parentPath=$(dirname ${{ env.PUBLISH_ANY_PATH }})
        tar -czvf "${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-fdd-any.tar.gz" -C "$parentPath" "$lastPart"

    - name: Archive [fde-win-x64]
      if: ${{ inputs.is-tool }}
      run: 7z a -tzip '${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-fde-win-x64.zip' '${{ env.PUBLISH_FDE_WIN_PATH }}'

    - name: Archive [fde-win-arm64]
      if: ${{ inputs.is-tool }}
      run: 7z a -tzip '${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-fde-win-arm64.zip' '${{ env.PUBLISH_FDE_WIN_ARM64_PATH }}'
      
    - name:  Archive [fde-osx-x64]
      if: ${{ inputs.is-tool }}
      run: |
        lastPart=$(basename ${{ env.PUBLISH_FDE_OSX_PATH }})
        parentPath=$(dirname ${{ env.PUBLISH_FDE_OSX_PATH }})
        tar -czvf "${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-fde-osx-x64.tar.gz" -C "$parentPath" "$lastPart"

    - name:  Archive [fde-osx-arm64]
      if: ${{ inputs.is-tool }}
      run: |
        lastPart=$(basename ${{ env.PUBLISH_FDE_OSX_ARM64_PATH }})
        parentPath=$(dirname ${{ env.PUBLISH_FDE_OSX_ARM64_PATH }})
        tar -czvf "${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-fde-osx-arm64.tar.gz" -C "$parentPath" "$lastPart"
        
    - name:  Archive [fde-linux-x64]
      if: ${{ inputs.is-tool }}
      run: |
        lastPart=$(basename ${{ env.PUBLISH_FDE_LINUX_PATH }})
        parentPath=$(dirname ${{ env.PUBLISH_FDE_LINUX_PATH }})
        tar -czvf "${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-fde-linux-x64.tar.gz" -C "$parentPath" "$lastPart"

    - name:  Archive [fde-linux-arm64]
      if: ${{ inputs.is-tool }}
      run: |
        lastPart=$(basename ${{ env.PUBLISH_FDE_LINUX_ARM64_PATH }})
        parentPath=$(dirname ${{ env.PUBLISH_FDE_LINUX_ARM64_PATH }})
        tar -czvf "${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-fde-linux-arm64.tar.gz" -C "$parentPath" "$lastPart"
        
    - name: Archive [scd-win-x64]
      if: ${{ inputs.is-tool }}
      run: 7z a -tzip '${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-scd-win-x64.zip' '${{ env.PUBLISH_SCD_WIN_PATH }}'

    - name: Archive [scd-win-arm64]
      if: ${{ inputs.is-tool }}
      run: 7z a -tzip '${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-scd-win-arm64.zip' '${{ env.PUBLISH_SCD_WIN_ARM64_PATH }}'
      
    - name:  Archive [scd-osx-x64]
      if: ${{ inputs.is-tool }}
      run: |
        lastPart=$(basename ${{ env.PUBLISH_SCD_OSX_PATH }})
        parentPath=$(dirname ${{ env.PUBLISH_SCD_OSX_PATH }})
        tar -czvf "${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-scd-osx-x64.tar.gz" -C "$parentPath" "$lastPart"

    - name:  Archive [scd-osx-arm64]
      if: ${{ inputs.is-tool }}
      run: |
        lastPart=$(basename ${{ env.PUBLISH_SCD_OSX_ARM64_PATH }})
        parentPath=$(dirname ${{ env.PUBLISH_SCD_OSX_ARM64_PATH }})
        tar -czvf "${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-scd-osx-arm64.tar.gz" -C "$parentPath" "$lastPart"
        
    - name:  Archive [scd-linux-x64]
      if: ${{ inputs.is-tool }}
      run: |
        lastPart=$(basename ${{ env.PUBLISH_SCD_LINUX_PATH }})
        parentPath=$(dirname ${{ env.PUBLISH_SCD_LINUX_PATH }})
        tar -czvf "${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-scd-linux-x64.tar.gz" -C "$parentPath" "$lastPart"

    - name:  Archive [scd-linux-arm64]
      if: ${{ inputs.is-tool }}
      run: |
        lastPart=$(basename ${{ env.PUBLISH_SCD_LINUX_ARM64_PATH }})
        parentPath=$(dirname ${{ env.PUBLISH_SCD_LINUX_ARM64_PATH }})
        tar -czvf "${{ runner.temp }}/${{ inputs.artifact-name-prefix }}.${{ env.version }}-scd-linux-arm64.tar.gz" -C "$parentPath" "$lastPart"
        
    - name: Upload artifacts [fdd-any] zip
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-fdd-any (zip)
        path: "${{ runner.temp }}/*-fdd-any.zip"
        if-no-files-found: error
        
    - name: Upload artifacts [fdd-any] tar
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-fdd-any (tar)
        path: "${{ runner.temp }}/*-fdd-any.tar.gz"
        if-no-files-found: error

    - name: Upload artifacts [fde-win-x64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-fde-win-x64
        path: "${{ runner.temp }}/*-fde-win-x64.zip"
        if-no-files-found: error

    - name: Upload artifacts [fde-win-arm64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-fde-win-arm64
        path: "${{ runner.temp }}/*-fde-win-arm64.zip"
        if-no-files-found: error
        
    - name: Upload artifacts [fde-osx-x64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-fde-osx-x64
        path: "${{ runner.temp }}/*-fde-osx-x64.tar.gz"
        if-no-files-found: error

    - name: Upload artifacts [fde-osx-arm64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-fde-osx-arm64
        path: "${{ runner.temp }}/*-fde-osx-arm64.tar.gz"
        if-no-files-found: error
        
    - name: Upload artifacts [fde-linux-x64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-fde-linux-x64
        path: "${{ runner.temp }}/*-fde-linux-x64.tar.gz"
        if-no-files-found: error

    - name: Upload artifacts [fde-linux-arm64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-fde-linux-arm64
        path: "${{ runner.temp }}/*-fde-linux-arm64.tar.gz"
        if-no-files-found: error
        
    - name: Upload artifacts [scd-win-x64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-scd-win-x64
        path: "${{ runner.temp }}/*-scd-win-x64.zip"
        if-no-files-found: error

    - name: Upload artifacts [scd-win-arm64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-scd-win-arm64
        path: "${{ runner.temp }}/*-scd-win-arm64.zip"
        if-no-files-found: error
        
    - name: Upload artifacts [scd-osx-x64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-scd-osx-x64
        path: "${{ runner.temp }}/*-scd-osx-x64.tar.gz"
        if-no-files-found: error

    - name: Upload artifacts [scd-osx-arm64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-scd-osx-arm64
        path: "${{ runner.temp }}/*-scd-osx-arm64.tar.gz"
        if-no-files-found: error
        
    - name: Upload artifacts [scd-linux-x64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-scd-linux-x64
        path: "${{ runner.temp }}/*-scd-linux-x64.tar.gz"
        if-no-files-found: error

    - name: Upload artifacts [scd-linux-arm64]
      if: ${{ inputs.is-tool }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-scd-linux-arm64
        path: "${{ runner.temp }}/*-scd-linux-arm64.tar.gz"
        if-no-files-found: error
        
    - name: Upload Artifacts - Nuget
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name-prefix }}-Nuget
        path: ${{ env.NUPKG_PATH }}/
        if-no-files-found: error
