name: Nuget Release

on:
  workflow_call:
    inputs:
      artificats-workflow:
        required: true
        type: string
      nuget-publish-env:
        required: true
        type: string
      nuget-publish-url:
        required: true
        type: string
    secrets:
      token:
        required: true
      nuget-api-token:
        required: true
        
env:
  ARTIFACTS: ./artifacts
  
jobs:
  nuget-publish:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.nuget-publish-env }}
      url: '${{ inputs.nuget-publish-url }}'
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.token }}
          workflow: ${{ inputs.artificats-workflow }}
          name: "-Nuget$"
          name_is_regexp: true
          path: ${{ env.ARTIFACTS }}
          
      - name: Use dotnet sdk
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Publish nuget
        run: dotnet nuget push ${{ env.ARTIFACTS }}/**/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json  
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.nuget-api-token }}
