name: Nuget Release

on:
  workflow_call:
    inputs:
      artifacts-workflow:
        required: true
        type: string
      nuget-publish-env:
        required: true
        type: string
    secrets:
      token:
        required: true
      nuget-user:
        required: true
        
env:
  ARTIFACTS: ./artifacts
  
jobs:
  nuget-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: ${{ inputs.nuget-publish-env }}
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v21
        with:
          github_token: ${{ secrets.token }}
          workflow: ${{ inputs.artifacts-workflow }}
          name: "-Nuget$"
          name_is_regexp: true
          path: ${{ env.ARTIFACTS }}

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.nuget-user }}
    
      - name: NuGet push
        run: dotnet nuget push ${{ env.ARTIFACTS }}/**/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
